name: DAST Analysis with OWASP ZAP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run OWASP ZAP Scan
      uses: zaproxy/action-full-scan@v0.1.0
      with:
        target: 'http://localhost:8080' # Replace by App's URL
        github_token: ${{ secrets.GITHUB_TOKEN }}
        app_username: ${{ secrets.APP_USERNAME }}
        app_password: ${{ secrets.APP_PASSWORD }} 
        docker_name: 'owasp/zap2docker-stable'
        rules_file_name: './zap-scan-configs/zap-config.xml'
        zap_options: '-config api.addrs.addr.name=localhost -config api.addrs.addr.regex=true'
