name: SAST with Bearer

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Build
        run: docker build -t bearer-sast .

      - name: Run Bearer SAST
        run: docker run --rm -v "${{ github.workspace }}:/workspace" bearer-sast ./run-bearer.sh /workspace
